# Generated by Django 5.2.17 on 2026-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_align_models_with_database_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysissession',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='clinical_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='post_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='pre_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='uf_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='uf_target',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
