# Generated by Django 5.2.17 on 2026-10-03 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_shift',
            field=models.CharField(blank=True, choices=[('SHIFT_1', 'Ca 1'), ('SHIFT_2', 'Ca 2'), ('SHIFT_3', 'Ca 3')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_pattern',
            field=models.CharField(blank=True, choices=[('T2_T4_T6', 'Thứ 2 - Thứ 4 - Thứ 6'), ('T3_T5_T7', 'Thứ 3 - Thứ 5 - Thứ 7')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_dialysis_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('fitness_score', models.FloatField(blank=True, null=True)),
                ('algorithm_metadata', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedule_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_plans', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_plans', to='core.department')),
            ],
            options={
                'ordering': ['-week_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('shift', models.CharField(choices=[('SHIFT_1', 'Ca 1'), ('SHIFT_2', 'Ca 2'), ('SHIFT_3', 'Ca 3')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('source', models.CharField(choices=[('GA', 'GA'), ('MANUAL', 'Manual')], default='GA', max_length=20)),
                ('original_shift', models.CharField(blank=True, choices=[('SHIFT_1', 'Ca 1'), ('SHIFT_2', 'Ca 2'), ('SHIFT_3', 'Ca 3')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='core.dialysismachine')),
                ('original_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.dialysismachine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='core.patient')),
                ('schedule_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.scheduleplan')),
            ],
            options={
                'ordering': ['scheduled_date', 'shift', 'machine'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduleplan',
            index=models.Index(fields=['department', 'week_start', 'status'], name='idx_plan_dept_week_status'),
        ),
        migrations.AddIndex(
            model_name='scheduleplan',
            index=models.Index(fields=['status'], name='idx_plan_status'),
        ),
        migrations.AddConstraint(
            model_name='scheduleplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('department', 'week_start'), name='uq_approved_plan_per_dept_week'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['schedule_plan', 'scheduled_date'], name='idx_asgn_plan_date'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['patient', 'scheduled_date'], name='idx_asgn_patient_date'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['machine', 'scheduled_date', 'shift'], name='idx_asgn_machine_date_shift'),
        ),
        migrations.AddConstraint(
            model_name='scheduleassignment',
            constraint=models.UniqueConstraint(fields=('schedule_plan', 'machine', 'scheduled_date', 'shift'), name='uq_asgn_plan_machine_date_shift'),
        ),
        migrations.AddConstraint(
            model_name='scheduleassignment',
            constraint=models.UniqueConstraint(fields=('schedule_plan', 'patient', 'scheduled_date'), name='uq_asgn_plan_patient_date'),
        ),
        migrations.AddConstraint(
            model_name='scheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='chk_asgn_start_before_end'),
        ),
    ]
