# Generated by Django 5.2.17 on 2026-10-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient_preferred_shift_patient_treatment_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysissession',
            name='schedule_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialysis_sessions', to='core.scheduleassignment'),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
